# MAVROS Distance Sensor Configuration
# This file enables the distance_sensor plugin for rangefinder support

# Plugin whitelist - explicitly enable distance_sensor
plugin_whitelist:
  - 'distance_sensor'
  - 'sys_*'
  - 'state'
  - 'command'
  - 'param'
  - 'mission'
  - 'setpoint'
  - 'setpoint_raw'
  - 'global_position'
  - 'local_position'
  - 'imu'
  - 'gps'
  - 'rc'
  - 'manual_control'
  - 'altitude'
  - 'attitude'
  - 'battery'
  - 'extended_state'
  - 'home_position'
  - 'landing_target'
  - 'mocap'
  - 'odometry'
  - 'terrain'
  - 'timesync_status'
  - 'vfr_hud'
  - 'waypoint'
  - 'waypoint_pull'
  - 'waypoint_push'

# Plugin blacklist - disable unnecessary plugins
plugin_blacklist:
  - actuator_control
  - ftp
  - safety_area
  - hil
  - image_pub
  - px4flow
  - vibration
  - vision_speed_estimate
  - wheel_odometry

# Distance sensor specific configuration
distance_sensor:
  rangefinder:
    id: 1
    orientation: 25  # Forward
    field_of_view: 0.1
    min_distance: 0.1
    max_distance: 50.0
    type: 1  # MAV_DISTANCE_SENSOR_LASER
